all:
	cd core && make 
	cd plugins/sample1 && make
	cd plugins/sample2 && make
install: 
	cd core && make install
	cd plugins/sample1 && make install
	cd plugins/sample2 && make install
run:
	cd core && ./core
