all:
	cd core && make 
	cd plugins/sample1 && make
	cd plugins/sample2 && make
install: 
	cd core && make install
	cd plugins/sample1 && make install
	cd plugins/sample2 && make install
clean: 
	cd core && make clean
	cd plugins/sample1 && make clean
	cd plugins/sample2 && make clean
run:
	cd core && ./core
